// Category-based fallback icons and categorization logic
import {
  Zap,
  Droplets,
  Flame,
  Wifi,
  Phone,
  Cable,
  Radio,
  Home,
  Building,
  Wrench,
  Lock,
  Car,
  Fuel,
  ParkingCircle,
  Shield,
  Heart,
  Umbrella,
  CreditCard,
  Building2,
  PiggyBank,
  Calculator,
  Cross,
  Pill,
  Stethoscope,
  Eye,
  Smile,
  Film,
  Music,
  Gamepad2,
  Newspaper,
  GraduationCap,
  Book,
  Laptop,
  Baby,
  Users,
  Scissors,
  Activity,
  UtensilsCrossed,
  Coffee,
  ShoppingCart,
  Briefcase,
  FileText,
  Printer,
  Receipt,
} from "../icons";

// Category-based fallback icons when provider matching fails
export const CATEGORY_FALLBACK_ICONS = {
  utilities: Zap,
  electric: Zap,
  electricity: Zap,
  gas: Flame,
  water: Droplets,
  internet: Wifi,
  phone: Phone,
  cable: Cable,
  satellite: Radio,

  housing: Home,
  rent: Home,
  mortgage: Home,
  hoa: Building,
  maintenance: Wrench,
  security: Lock,

  transportation: Car,
  car: Car,
  auto: Car,
  fuel: Fuel,
  parking: ParkingCircle,

  insurance: Shield,
  health: Heart,
  medical: Cross,
  dental: Smile,
  vision: Eye,
  life: Umbrella,

  financial: CreditCard,
  credit: CreditCard,
  loan: Building2,
  bank: Building2,
  savings: PiggyBank,
  investment: PiggyBank,
  tax: Calculator,

  healthcare: Cross,
  pharmacy: Pill,
  doctor: Stethoscope,

  entertainment: Film,
  streaming: Film,
  music: Music,
  gaming: Gamepad2,
  news: Newspaper,

  education: GraduationCap,
  tuition: GraduationCap,
  books: Book,
  software: Laptop,
  tech: Laptop,

  personal: Scissors,
  family: Users,
  childcare: Baby,
  fitness: Activity,
  gym: Activity,

  food: UtensilsCrossed,
  dining: UtensilsCrossed,
  restaurant: UtensilsCrossed,
  grocery: ShoppingCart,
  shopping: ShoppingCart,
  coffee: Coffee,

  business: Briefcase,
  professional: FileText,
  office: Printer,

  // Default
  bills: Receipt,
  other: Receipt,
};

// Category detection patterns for auto-categorization
export const CATEGORY_PATTERNS = {
  utilities: [
    "electric",
    "electricity",
    "power",
    "energy",
    "gas",
    "natural gas",
    "water",
    "sewer",
    "wastewater",
    "internet",
    "wifi",
    "broadband",
    "phone",
    "cellular",
    "wireless",
    "cable",
    "satellite",
  ],

  housing: [
    "rent",
    "mortgage",
    "hoa",
    "homeowners",
    "property management",
    "landlord",
    "maintenance",
    "repair",
    "security system",
  ],

  transportation: [
    "car payment",
    "auto loan",
    "car insurance",
    "gas",
    "fuel",
    "parking",
    "toll",
    "registration",
    "dmv",
  ],

  insurance: [
    "insurance",
    "health insurance",
    "medical insurance",
    "auto insurance",
    "car insurance",
    "home insurance",
    "renters insurance",
    "life insurance",
    "dental insurance",
    "vision insurance",
  ],

  financial: [
    "credit card",
    "loan",
    "mortgage",
    "bank",
    "savings",
    "investment",
    "retirement",
    "401k",
    "ira",
    "tax",
  ],

  healthcare: [
    "doctor",
    "medical",
    "hospital",
    "clinic",
    "pharmacy",
    "prescription",
    "dental",
    "dentist",
    "vision",
    "eye care",
    "health",
  ],

  entertainment: [
    "netflix",
    "hulu",
    "disney",
    "streaming",
    "music",
    "spotify",
    "gaming",
    "gym",
    "fitness",
    "subscription",
  ],

  education: [
    "tuition",
    "school",
    "university",
    "college",
    "education",
    "books",
    "supplies",
    "software",
    "tech",
  ],

  food: [
    "restaurant",
    "dining",
    "food",
    "grocery",
    "supermarket",
    "coffee",
    "uber eats",
    "doordash",
    "delivery",
  ],

  business: [
    "business",
    "professional",
    "office",
    "supplies",
    "service",
    "consulting",
    "software",
    "subscription",
  ],
};
