// Bill provider/company patterns with specific icons
import {
  Zap,
  Droplets,
  Flame,
  Wifi,
  Phone,
  Cable,
  Radio,
  Home,
  Shield,
  CreditCard,
  Cross,
  Film,
  Music,
  GraduationCap,
  UtensilsCrossed,
  Coffee,
  ShoppingCart,
  Car,
  Fuel,
  Activity,
  Receipt,
} from "../icons";

// Company-specific icon mappings based on provider names
export const BILL_PROVIDER_ICONS = {
  // Electric Companies
  "pg&e": Zap,
  "pacific gas & electric": Zap,
  "southern california edison": Zap,
  sce: Zap,
  "duke energy": Zap,
  "florida power": Zap,
  electric: Zap,
  "power company": Zap,
  electricity: Zap,
  energy: Zap,

  // Water/Sewer Companies
  "water department": Droplets,
  "water district": Droplets,
  "municipal water": Droplets,
  "water company": Droplets,
  sewer: Droplets,
  wastewater: Droplets,
  "water & sewer": Droplets,

  // Gas Companies
  "southern california gas": Flame,
  "socal gas": Flame,
  "national grid": Flame,
  "columbia gas": Flame,
  "peoples gas": Flame,
  "gas company": Flame,
  "natural gas": Flame,

  // Internet/Cable/Phone
  comcast: Wifi,
  xfinity: Wifi,
  verizon: Phone,
  att: Phone,
  "at&t": Phone,
  spectrum: Cable,
  "time warner": Cable,
  cox: Cable,
  directv: Radio,
  dish: Radio,
  satellite: Radio,
  internet: Wifi,
  cable: Cable,
  phone: Phone,
  wireless: Phone,
  cellular: Phone,
  broadband: Wifi,
  fiber: Wifi,

  // Housing
  rent: Home,
  mortgage: Home,
  "property management": Home,
  hoa: Home,
  "homeowners association": Home,
  "condo association": Home,
  landlord: Home,

  // Insurance Companies
  "state farm": Shield,
  geico: Shield,
  progressive: Shield,
  allstate: Shield,
  farmers: Shield,
  usaa: Shield,
  insurance: Shield,
  "auto insurance": Shield,
  "car insurance": Shield,
  "health insurance": Cross,
  "medical insurance": Cross,
  "life insurance": Shield,
  "home insurance": Shield,
  "renters insurance": Shield,

  // Financial/Credit
  chase: CreditCard,
  "bank of america": CreditCard,
  "wells fargo": CreditCard,
  citibank: CreditCard,
  "capital one": CreditCard,
  discover: CreditCard,
  "american express": CreditCard,
  amex: CreditCard,
  "credit card": CreditCard,
  loan: CreditCard,
  bank: CreditCard,

  // Streaming/Entertainment
  netflix: Film,
  hulu: Film,
  disney: Film,
  "amazon prime": Film,
  hbo: Film,
  youtube: Film,
  spotify: Music,
  "apple music": Music,
  pandora: Music,
  streaming: Film,
  music: Music,

  // Education
  tuition: GraduationCap,
  school: GraduationCap,
  university: GraduationCap,
  college: GraduationCap,
  education: GraduationCap,

  // Food/Dining
  "uber eats": UtensilsCrossed,
  doordash: UtensilsCrossed,
  grubhub: UtensilsCrossed,
  restaurant: UtensilsCrossed,
  starbucks: Coffee,
  coffee: Coffee,
  grocery: ShoppingCart,
  supermarket: ShoppingCart,
  walmart: ShoppingCart,
  target: ShoppingCart,
  costco: ShoppingCart,
  safeway: ShoppingCart,

  // Transportation
  "car payment": Car,
  "auto loan": Car,
  "gas station": Fuel,
  shell: Fuel,
  chevron: Fuel,
  exxon: Fuel,
  bp: Fuel,
  fuel: Fuel,
  gasoline: Fuel,

  // Fitness/Health
  gym: Activity,
  fitness: Activity,
  "24 hour fitness": Activity,
  "planet fitness": Activity,
  "la fitness": Activity,
  ymca: Activity,
  "health club": Activity,

  // Default fallback
  bill: Receipt,
  payment: Receipt,
};
