#!/bin/bash

# This script processes the ESLint JSON output and creates a sorted, readable report.

# --- Configuration ---
# The location of the JSON file generated by `npm run lint:json`
INPUT_FILE="docs/audits/lint-results.json"
# The location for the generated report
OUTPUT_FILE="docs/audits/sorted-lint-report.txt"

# --- Pre-flight checks ---
# Check if jq is installed, as it's required for JSON parsing.
if ! command -v jq &> /dev/null; then
    echo "Error: jq is not installed. Please install it to continue." >&2
    exit 1
fi

# Check if the input file exists.
if [ ! -f "$INPUT_FILE" ]; then
    echo "Error: Lint results file not found at '$INPUT_FILE'" >&2
    echo "Please run 'npm run lint:json' first." >&2
    exit 1
fi

# --- Report Generation ---
# Clear the output file to ensure a fresh report.
> "$OUTPUT_FILE"

# Section 1: Summary of files with the most issues.
echo "--- Files with Most Issues (Errors + Warnings) ---" >> "$OUTPUT_FILE"
jq -r '.[] | select((.errorCount + .warningCount) > 0) | "\((.errorCount + .warningCount)) issues in \(.filePath)"' "$INPUT_FILE" | sort -nr >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Section 2: Breakdown of issues by ESLint rule.
echo "--- Issue Count by Category (ESLint Rule) ---" >> "$OUTPUT_FILE"
jq -r '.[].messages[].ruleId' "$INPUT_FILE" | sort | uniq -c | sort -nr >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Section 3: A detailed, classic lint-style report.
echo "--- Detailed Lint Report ---" >> "$OUTPUT_FILE"
jq -r '.[] | .filePath as $file | .messages[] | "\($file):\(.line):\(.column) - \(.severity) - \(.message) (\(.ruleId))"' "$INPUT_FILE" >> "$OUTPUT_FILE"

# --- Completion ---
echo "Sorted lint report has been generated at '$OUTPUT_FILE'"
