name: CI - Develop Branch

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Auto-fix formatting
        run: npm run format

      - name: Check for formatting changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Code was auto-formatted. Committing changes..."
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "style: auto-fix prettier formatting"
            
            # Fix detached HEAD issue by ensuring we're on the right branch
            if [ "${{ github.event_name }}" == "pull_request" ]; then
              # For PRs, push to the PR branch
              BRANCH_NAME="${{ github.head_ref }}"
              echo "Pushing to PR branch: $BRANCH_NAME"
              git push origin HEAD:$BRANCH_NAME
            else
              # For push events, push to the current branch
              BRANCH_NAME="${{ github.ref_name }}"
              echo "Pushing to branch: $BRANCH_NAME"
              git push origin HEAD:$BRANCH_NAME
            fi
          else
            echo "No formatting changes needed"
          fi

      - name: Lint
        run: npm run lint

      - name: Test with Coverage
        run: npm run test:ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Build
        run: npm run build

      - name: Check for build output
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed - no dist directory found"
            exit 1
          fi
          if [ ! -f "dist/index.html" ]; then
            echo "Build failed - no index.html found"
            exit 1
          fi
          echo "Build completed successfully"
